### ISSUE TITLE
Question about .off

### ISSUE THREAD

**Issue by smilehyun** [fasttime/art#1]
Hello,
I found your library is very interesting, and I have a question while I tried to use it.

I'm trying to use it to generate template for custom element. so I register them on createdCallback, or attachedCallback. My element has some event listener attached by using art.on() method.

However, I want to remove certain events from my elements in some cases , but i'n not sure how I can remove them my art template. Should i regenerate template with art.off() and replace entire template? OR is there an easier way to do it? Basically, I like to know how i can dynamically add or remove events.

Cheers!

**Comment by fasttime** [comment]
Hello! Thanks for reminding me that the documentation here needs more work 😄 

`art.off()` expects the same parameters passed to `art.on()` and must be called on the same target element.

This means that both the function that handles the event and the element itself must be _remembered_ in a local variable or in some property.

```js
function handleClick()
{
    alert("You clicked here!");
}

var button1 =
    art(
        "input",
        { type: "button", value: "Click here" },
        art.on("click", handleClick)
    );
```

The example above creates a button with a click event handler attached. To remove the event handler with `art.off`:

```js
art(button1, art.off("click", handleClick));
```

To re-add the handler later:

```js
art(button1, art.on("click", handleClick));
```

Please, let me know if this helps with your problem or if it's still missing something, so I can improve the documentation.
